<?php

echo 'Nama : ';
echo 'Ahmad Shofi Muharom';

echo "\n";

echo 'Nama : ';
echo "Ahmad\t Shofi Muharom";

echo "\n";


// Heredoc
echo <<<TEXT
FSDHFLKJLKFCLSJFCNSLFJCSLKDFJCLKFCNSLFJCS
SFHLSCFNLSKFJLKCSJFLKSCNLSKNCLKSJFCSLJCFN
CKFNLKSFHNCKSDCFHKSLDFNCSKFHCNLSNCFLNSDC
ACKLFNCKLSDFNHKLCNFCFNSJFCLKNFCLSKFCKSNSCNF
TEXT;

//NOWdoc
echo <<<'TEXT'
FSDHFLKJLKFCLSJFCNSLFJCSLKDFJCLKFCNSLFJCS
SFHLSCFNLSKFJLKCSJFLKSCNLSKNCLKSJFCSLJCFN
CKFNLKSFHNCKSDCFHKSLDFNCSKFHCNLSNCFLNSDC
ACKLFNCKLSDFNHKLCNFCFNSJFCLKNFCLSKFCKSNSCNF
TEXT;
